const jobInfo =[
  {
    ctmid: "6271848",
    jobid: "141817489",
    jobname: "客户工程师 (北京)",
    coname: "中国电信集团有限公司",
    coid: "7324396",
    divid: "4577135",
    divname: "云网运营部",
    jobareaname: "北京",
    workareaname: "北京",
    issuedate: "2022-10-10 13:31:32",
    address: "",
    poscode: "",
    status: "24",
    jobnum: "",
    jkeyword: "",
    degreefrom: "硕士",
    workyearname: "在校生/应届生",
    monthlysalary: "8000-9999",
    providesalarname: "",
    term: "全职",
    joborder: "0",
    ejobareaname: "Beijing",
    eworkareaname: "Beijing",
    eworkyearname: "Student/Fresh Graduate",
    edegreefrom: "Master",
    funtype: "大学/大专应届毕业生",
    efuntype: "University/College Graduating Student",
    mark: "",
  },
  {
    ctmid: "6271848",
    jobid: "141817501",
    jobname: "5G业务运营维护 (北京)",
    coname: "中国电信集团有限公司",
    coid: "7324396",
    divid: "4577135",
    divname: "云网运营部",
    jobareaname: "北京",
    workareaname: "北京",
    issuedate: "2022-10-10 13:31:32",
    address: "",
    poscode: "",
    status: "24",
    jobnum: "",
    jkeyword: "",
    degreefrom: "硕士",
    workyearname: "在校生/应届生",
    monthlysalary: "8000-9999",
    providesalarname: "",
    term: "全职",
    joborder: "0",
    ejobareaname: "Beijing",
    eworkareaname: "Beijing",
    eworkyearname: "Student/Fresh Graduate",
    edegreefrom: "Master",
    funtype: "大学/大专应届毕业生",
    efuntype: "University/College Graduating Student",
    mark: "",
  },
  {
    ctmid: "6271848",
    jobid: "141817514",
    jobname: "云计算运维开发工程师 (北京)",
    coname: "中国电信集团有限公司",
    coid: "7324396",
    divid: "4577135",
    divname: "云网运营部",
    jobareaname: "北京",
    workareaname: "北京",
    issuedate: "2022-10-10 13:31:29",
    address: "",
    poscode: "",
    status: "24",
    jobnum: "",
    jkeyword: "",
    degreefrom: "硕士",
    workyearname: "在校生/应届生",
    monthlysalary: "8000-9999",
    providesalarname: "",
    term: "全职",
    joborder: "0",
    ejobareaname: "Beijing",
    eworkareaname: "Beijing",
    eworkyearname: "Student/Fresh Graduate",
    edegreefrom: "Master",
    funtype: "大学/大专应届毕业生",
    efuntype: "University/College Graduating Student",
    mark: "",
  },
  {
    ctmid: "6271848",
    jobid: "141817534",
    jobname: "软件运营开发岗（上海）",
    coname: "中国电信集团有限公司",
    coid: "7324396",
    divid: "4577135",
    divname: "云网运营部",
    jobareaname: "上海",
    workareaname: "上海",
    issuedate: "2022-10-10 13:31:28",
    address: "",
    poscode: "",
    status: "24",
    jobnum: "",
    jkeyword: "",
    degreefrom: "本科",
    workyearname: "在校生/应届生",
    monthlysalary: "8000-9999",
    providesalarname: "",
    term: "全职",
    joborder: "0",
    ejobareaname: "Shanghai",
    eworkareaname: "Shanghai",
    eworkyearname: "Student/Fresh Graduate",
    edegreefrom: "Bachelor",
    funtype: "大学/大专应届毕业生",
    efuntype: "University/College Graduating Student",
    mark: "",
  },
  {
    ctmid: "6271848",
    jobid: "141817554",
    jobname: "数据应用推进岗（上海）",
    coname: "中国电信集团有限公司",
    coid: "7324396",
    divid: "4577135",
    divname: "云网运营部",
    jobareaname: "上海",
    workareaname: "上海",
    issuedate: "2022-10-10 13:31:31",
    address: "",
    poscode: "",
    status: "24",
    jobnum: "",
    jkeyword: "",
    degreefrom: "本科",
    workyearname: "在校生/应届生",
    monthlysalary: "8000-9999",
    providesalarname: "",
    term: "全职",
    joborder: "0",
    ejobareaname: "Shanghai",
    eworkareaname: "Shanghai",
    eworkyearname: "Student/Fresh Graduate",
    edegreefrom: "Bachelor",
    funtype: "大学/大专应届毕业生",
    efuntype: "University/College Graduating Student",
    mark: "",
  },
  {
    ctmid: "6271848",
    jobid: "141817591",
    jobname: "云网运营调度工程师（上海）",
    coname: "中国电信集团有限公司",
    coid: "7324396",
    divid: "4577135",
    divname: "云网运营部",
    jobareaname: "上海",
    workareaname: "上海",
    issuedate: "2022-10-10 13:31:32",
    address: "",
    poscode: "",
    status: "24",
    jobnum: "",
    jkeyword: "",
    degreefrom: "本科",
    workyearname: "在校生/应届生",
    monthlysalary: "8000-9999",
    providesalarname: "",
    term: "全职",
    joborder: "0",
    ejobareaname: "Shanghai",
    eworkareaname: "Shanghai",
    eworkyearname: "Student/Fresh Graduate",
    edegreefrom: "Bachelor",
    funtype: "大学/大专应届毕业生",
    efuntype: "University/College Graduating Student",
    mark: "",
  },
  {
    ctmid: "6271848",
    jobid: "143602456",
    jobname: "网络与信息安全工程师（北京）",
    coname: "中国电信集团有限公司",
    coid: "7324396",
    divid: "4577135",
    divname: "云网运营部",
    jobareaname: "北京",
    workareaname: "北京",
    issuedate: "2022-11-03 04:00:31",
    address: "",
    poscode: "",
    status: "24",
    jobnum: "",
    jkeyword: "",
    degreefrom: "硕士",
    workyearname: "在校生/应届生",
    monthlysalary: "8000-9999",
    providesalarname: "",
    term: "全职",
    joborder: "0",
    ejobareaname: "Beijing",
    eworkareaname: "Beijing",
    eworkyearname: "Student/Fresh Graduate",
    edegreefrom: "Master",
    funtype: "研究生",
    efuntype: "Graduate Student",
    mark: "",
  },
  {
    ctmid: "6271848",
    jobid: "143633014",
    jobname: "软件产品经理岗（北京）",
    coname: "中国电信集团有限公司",
    coid: "7324396",
    divid: "4577135",
    divname: "云网运营部",
    jobareaname: "北京",
    workareaname: "北京",
    issuedate: "2022-11-03 04:00:31",
    address: "",
    poscode: "",
    status: "24",
    jobnum: "",
    jkeyword: "",
    degreefrom: "硕士",
    workyearname: "在校生/应届生",
    monthlysalary: "8000-9999",
    providesalarname: "8千-1.6万",
    term: "全职",
    joborder: "0",
    ejobareaname: "Beijing",
    eworkareaname: "Beijing",
    eworkyearname: "Student/Fresh Graduate",
    edegreefrom: "Master",
    funtype: "大学/大专应届毕业生",
    efuntype: "University/College Graduating Student",
    mark: "",
  },
  {
    ctmid: "6271848",
    jobid: "143633022",
    jobname: "PaaS维护支撑岗（北京）",
    coname: "中国电信集团有限公司",
    coid: "7324396",
    divid: "4577135",
    divname: "云网运营部",
    jobareaname: "北京",
    workareaname: "北京",
    issuedate: "2022-11-03 04:00:31",
    address: "",
    poscode: "",
    status: "24",
    jobnum: "",
    jkeyword: "",
    degreefrom: "硕士",
    workyearname: "在校生/应届生",
    monthlysalary: "8000-9999",
    providesalarname: "8千-1.6万",
    term: "全职",
    joborder: "0",
    ejobareaname: "Beijing",
    eworkareaname: "Beijing",
    eworkyearname: "Student/Fresh Graduate",
    edegreefrom: "Master",
    funtype: "大学/大专应届毕业生",
    efuntype: "University/College Graduating Student",
    mark: "",
  },
  {
    ctmid: "6271848",
    jobid: "143633027",
    jobname: "业务需求分析岗（北京）",
    coname: "中国电信集团有限公司",
    coid: "7324396",
    divid: "4577135",
    divname: "云网运营部",
    jobareaname: "北京",
    workareaname: "北京",
    issuedate: "2022-11-03 04:00:31",
    address: "",
    poscode: "",
    status: "24",
    jobnum: "",
    jkeyword: "",
    degreefrom: "硕士",
    workyearname: "在校生/应届生",
    monthlysalary: "8000-9999",
    providesalarname: "8千-1.6万",
    term: "全职",
    joborder: "0",
    ejobareaname: "Beijing",
    eworkareaname: "Beijing",
    eworkyearname: "Student/Fresh Graduate",
    edegreefrom: "Master",
    funtype: "大学/大专应届毕业生",
    efuntype: "University/College Graduating Student",
    mark: "",
  },
],