/*
 * @Author: zhuziqiang z2206071258@163.com
 * @Date: 2022-11-05 17:09:19
 * @LastEditors: zhuziqiang z2206071258@163.com
 * @LastEditTime: 2022-11-05 17:20:20
 */
let jobs = [
  {
    idRecruitPosition: 699,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 700,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Hardware_class",
    positionTypeName: "硬件类",
    positionName: "衍射光学工程师",
    positionDesc:
      "1.负责AR衍射光波导的研发工作，设计系统架构，并进行具体方案的仿真优化；\n2.确定光学元件的加工方案，配合工艺、生产团队，基于设计参数和容差分析，将设计导入产品制作，协助研发、优化产品的生产工艺；\n3.负责测试方案的制定，以及从设计到样品转换过程中的相关技术问题的解决；\n4.定义与评审AR显示光学技术路线，探索先进光学技术在AR显示中的应用；\n5.跟踪并分析国内外AR/VR相关领域资讯和前沿技术，构思撰写相关专利。",
    positionRequire:
      "1.物理学、计算电磁学、光学、仪器科学、光电子等相关专业；\n2.具备良好的物理光学、信息光学基础，熟悉衍射光学理论，具备光栅等衍射光学器件的设计经验者优先；\n3.了解严格耦合波、时域有限差分等计算电磁学理论，并具备至少一种理论算法的代码实现经验；\n4.熟悉遗传、粒子群等优化算法，具备至少一种优化算法的使用经验；\n5.熟练使用Matlab或C++等编程语言；\n6.使用过FDTD solutions、Comsol或RSoft软件的一种或以上者优先；\n7.勇于探索，对新技术抱有强烈好奇心和自驱力。\n\n学历要求：硕士及以上",
    workCityName: "深圳",
    workCityCode: "10002",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 7,
    positionStatus: 0,
    idProjPosition: 699,
    projectPositionId: 700,
    projectPositionName: "衍射光学工程师",
    projectPositionDesc:
      "1.负责AR衍射光波导的研发工作，设计系统架构，并进行具体方案的仿真优化；\n2.确定光学元件的加工方案，配合工艺、生产团队，基于设计参数和容差分析，将设计导入产品制作，协助研发、优化产品的生产工艺；\n3.负责测试方案的制定，以及从设计到样品转换过程中的相关技术问题的解决；\n4.定义与评审AR显示光学技术路线，探索先进光学技术在AR显示中的应用；\n5.跟踪并分析国内外AR/VR相关领域资讯和前沿技术，构思撰写相关专利。",
    projectPositionRequire:
      "1.物理学、计算电磁学、光学、仪器科学、光电子等相关专业；\n2.具备良好的物理光学、信息光学基础，熟悉衍射光学理论，具备光栅等衍射光学器件的设计经验者优先；\n3.了解严格耦合波、时域有限差分等计算电磁学理论，并具备至少一种理论算法的代码实现经验；\n4.熟悉遗传、粒子群等优化算法，具备至少一种优化算法的使用经验；\n5.熟练使用Matlab或C++等编程语言；\n6.使用过FDTD solutions、Comsol或RSoft软件的一种或以上者优先；\n7.勇于探索，对新技术抱有强烈好奇心和自驱力。\n\n学历要求：硕士及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 497,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 502,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Engineering_Technology",
    positionTypeName: "工程技术类",
    positionName: "TE工程师",
    positionDesc:
      "在这里，你将获得为业内领先的智能终端提供测试平台/方案的机会，你将接触到高度自动化的精密生产车间及业内先进的测试方案和智能制造，你将感受到最年轻化的团队作战氛围，加入我们，让我们一起迸发青春的火花，让我们一起智造未来。\n具体工作方向包括：\n1.运用专业知识为智能手机提供先进的生产测试方案；\n2.智能制造平台搭建和优化；\n3.支撑公司产品的研发，新技术生产测试方案的实现，保证产品品质。",
    positionRequire:
      "1.计算机科学与技术、电子信息工程、通信工程相关专业；\n2.熟练使用VC++MFC编程；\n3.良好的逻辑分析能力和沟通表达能力；\n我们更希望你：\r\n1.英语六级及以上，听说读写熟练；\r\n2.具备优秀的组织协调能力和团队合作能力，乐于奉献。\n\n学历要求：本科及以上",
    workCityName: "东莞",
    workCityCode: "10001",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 19,
    positionStatus: 0,
    idProjPosition: 497,
    projectPositionId: 502,
    projectPositionName: "TE工程师",
    projectPositionDesc:
      "在这里，你将获得为业内领先的智能终端提供测试平台/方案的机会，你将接触到高度自动化的精密生产车间及业内先进的测试方案和智能制造，你将感受到最年轻化的团队作战氛围，加入我们，让我们一起迸发青春的火花，让我们一起智造未来。\n具体工作方向包括：\n1.运用专业知识为智能手机提供先进的生产测试方案；\n2.智能制造平台搭建和优化；\n3.支撑公司产品的研发，新技术生产测试方案的实现，保证产品品质。",
    projectPositionRequire:
      "1.计算机科学与技术、电子信息工程、通信工程相关专业；\n2.熟练使用VC++MFC编程；\n3.良好的逻辑分析能力和沟通表达能力；\n我们更希望你：\r\n1.英语六级及以上，听说读写熟练；\r\n2.具备优秀的组织协调能力和团队合作能力，乐于奉献。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 494,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 501,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Engineering_Technology",
    positionTypeName: "工程技术类",
    positionName: "SMT PE工程师",
    positionDesc:
      "在这里，你将获得为业内领先的智能终端提供技术支持的机会，你将接触到高度自动化的精密生产车间，你将领略到至美的前沿科技和先进的自动化设备，你将感受到最年轻化的团队作战氛围，加入我们，让我们一起迸发青春的火花，让我们一起智造未来。\n具体工作方向包括：\n1..负责手机产品的工艺方案验证，保证产品焊接水平和生产可靠性；\n2.运用专业知识进行设备改善及优化；\n3.设备日常管理，实现稳定高效运行。",
    positionRequire:
      "1.机械制造及自动化相关专业；\n2.熟悉电路图基本原理；\n3.有良好的分析思维能力、沟通表达能力；\n我们更希望你：\r\n1.英语六级及以上，听说读写熟练；\r\n2.具备优秀的组织协调能力和团队合作能力，乐于奉献。\n\n学历要求：本科及以上",
    workCityName: "东莞",
    workCityCode: "10001",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 29,
    positionStatus: 0,
    idProjPosition: 494,
    projectPositionId: 501,
    projectPositionName: "SMT PE工程师",
    projectPositionDesc:
      "在这里，你将获得为业内领先的智能终端提供技术支持的机会，你将接触到高度自动化的精密生产车间，你将领略到至美的前沿科技和先进的自动化设备，你将感受到最年轻化的团队作战氛围，加入我们，让我们一起迸发青春的火花，让我们一起智造未来。\n具体工作方向包括：\n1..负责手机产品的工艺方案验证，保证产品焊接水平和生产可靠性；\n2.运用专业知识进行设备改善及优化；\n3.设备日常管理，实现稳定高效运行。",
    projectPositionRequire:
      "1.机械制造及自动化相关专业；\n2.熟悉电路图基本原理；\n3.有良好的分析思维能力、沟通表达能力；\n我们更希望你：\r\n1.英语六级及以上，听说读写熟练；\r\n2.具备优秀的组织协调能力和团队合作能力，乐于奉献。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 491,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 499,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Engineering_Technology",
    positionTypeName: "工程技术类",
    positionName: "ME工程师",
    positionDesc:
      "在这里，你将获得为业内领先的智能终端提供技术支持的机会，你将接触到高度自动化的精密生产车间，你将领略到至美的前沿科技和先进的测试手段，你将感受到最年轻化的团队作战氛围，加入我们，让我们一起迸发青春的火花，让我们一起智造未来。\n具体工作方向包括：\n1.整合供应商资源，探讨最优设备方案，进行自动化设备导入；\n2.运用专业知识进行设备改善及优化；\n3.设备日常管理，实现稳定高效运行。",
    positionRequire:
      "1.电气自动化、机电一体化相关专业；\n2.熟悉PLC原理与应用、运动控制系统；\n3.有良好的分析思维能力、沟通表达能力；\n我们更希望你：\r\n1.英语六级及以上，听说读写熟练；\r\n2.具备优秀的组织协调能力和团队合作能力，乐于奉献。\n\n学历要求：本科及以上",
    workCityName: "东莞,重庆",
    workCityCode: "10001,10009",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 33.33333333,
    positionStatus: 0,
    idProjPosition: 491,
    projectPositionId: 499,
    projectPositionName: "ME工程师",
    projectPositionDesc:
      "在这里，你将获得为业内领先的智能终端提供技术支持的机会，你将接触到高度自动化的精密生产车间，你将领略到至美的前沿科技和先进的测试手段，你将感受到最年轻化的团队作战氛围，加入我们，让我们一起迸发青春的火花，让我们一起智造未来。\n具体工作方向包括：\n1.整合供应商资源，探讨最优设备方案，进行自动化设备导入；\n2.运用专业知识进行设备改善及优化；\n3.设备日常管理，实现稳定高效运行。",
    projectPositionRequire:
      "1.电气自动化、机电一体化相关专业；\n2.熟悉PLC原理与应用、运动控制系统；\n3.有良好的分析思维能力、沟通表达能力；\n我们更希望你：\r\n1.英语六级及以上，听说读写熟练；\r\n2.具备优秀的组织协调能力和团队合作能力，乐于奉献。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 496,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 503,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Engineering_Technology",
    positionTypeName: "工程技术类",
    positionName: "电子PE工程师",
    positionDesc:
      "在这里，你将制造业内领先的智能终端，你将接触高度自动化的精密制造基地，你将领略到引领潮流的科技之美，你将感受到最年轻化的团队作战氛围，加入我们，让我们一起迸发青春的火花，让我们一起智造未来。\n具体工作方向包括：\n1.运用电子、通信类等专业知识为智能手机制造保驾护航，排忧解难；\n2.时刻站在用户角度，分析产品失效原因；\n3.不遗余力提升制造水平，推动供应商质量问题解决，打造伟大产品；\n4.支撑公司产品的开发，新技术和新工艺的实现，兼顾可制造性，保证生产直通率。",
    positionRequire:
      "1.电子、通信、材料类相关专业；\n2.熟悉模电、数电、通讯原理基础知识；\n3.有良好的分析思维能力、沟通表达能力；\n我们更希望你：\n1.英语六级及以上，听说读写熟练；\n2.具备优秀的组织协调能力和团队合作能力，乐于奉献。\n\n学历要求：本科及以上",
    workCityName: "东莞",
    workCityCode: "10001",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 34.5,
    positionStatus: 0,
    idProjPosition: 496,
    projectPositionId: 503,
    projectPositionName: "电子PE工程师",
    projectPositionDesc:
      "在这里，你将制造业内领先的智能终端，你将接触高度自动化的精密制造基地，你将领略到引领潮流的科技之美，你将感受到最年轻化的团队作战氛围，加入我们，让我们一起迸发青春的火花，让我们一起智造未来。\n具体工作方向包括：\n1.运用电子、通信类等专业知识为智能手机制造保驾护航，排忧解难；\n2.时刻站在用户角度，分析产品失效原因；\n3.不遗余力提升制造水平，推动供应商质量问题解决，打造伟大产品；\n4.支撑公司产品的开发，新技术和新工艺的实现，兼顾可制造性，保证生产直通率。",
    projectPositionRequire:
      "1.电子、通信、材料类相关专业；\n2.熟悉模电、数电、通讯原理基础知识；\n3.有良好的分析思维能力、沟通表达能力；\n我们更希望你：\n1.英语六级及以上，听说读写熟练；\n2.具备优秀的组织协调能力和团队合作能力，乐于奉献。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 698,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 699,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Hardware_class",
    positionTypeName: "硬件类",
    positionName: "光学工程师（健康方向）",
    positionDesc:
      "1.负责人体生理参数检测光学传感器组件选型、仿真及设计；\n2.负责人体形态、运动姿势识别等光学系统选型、仿真及设计。",
    positionRequire:
      "1.光学工程、光电技术、光电一体化等相关专业；\n2.至少熟练一种光学软件，并可以进行非序列光学设计优化；\n3.深入理解光学系统的误差分析与配合；\n4.良好的团队协作能力和学习能力；\n我们更希望你：\n具备穿戴式光学传感器、结构光等设计经验。\n\n学历要求：硕士及以上",
    workCityName: "深圳",
    workCityCode: "10002",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 41,
    positionStatus: 0,
    idProjPosition: 698,
    projectPositionId: 699,
    projectPositionName: "光学工程师（健康方向）",
    projectPositionDesc:
      "1.负责人体生理参数检测光学传感器组件选型、仿真及设计；\n2.负责人体形态、运动姿势识别等光学系统选型、仿真及设计。",
    projectPositionRequire:
      "1.光学工程、光电技术、光电一体化等相关专业；\n2.至少熟练一种光学软件，并可以进行非序列光学设计优化；\n3.深入理解光学系统的误差分析与配合；\n4.良好的团队协作能力和学习能力；\n我们更希望你：\n具备穿戴式光学传感器、结构光等设计经验。\n\n学历要求：硕士及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 505,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 512,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Sales_service",
    positionTypeName: "销售服务类",
    positionName: "销售管理培训生",
    positionDesc:
      "如果你：\n-热爱挑战，渴望在实践中学习销售管理技能，挑战区域市场管理目标和销售目标；\n-热爱探索，不断开拓新兴市场，不断实践新运营之道，进行全球范围的区域性统筹管理；\n-渴望成功，有远大的抱负，不甘于平庸，期待更快的成长；\n那么，欢迎加入我们，成为一名OPPO销售管理培训生！\n\n加入我们，你将：\n-这里是OPPO销售精英成长的摇篮，以区域市场操盘为实践主线，辅以渠道、零售、GTM等销售职能模块的历练，建立对销售领域的全面认知；\n-接受系统化的专业培养，给予完善的销售领域课程培训，专家导师全程跟踪辅导，业务和管理能力全面覆盖；\n-快速成长为销售领域负责人，主导销售实战，助力OPPO销售业务成功。\n",
    positionRequire:
      "1.性格外向，善于沟通，能快速建立社交圈；\n2.充满激情，热爱挑战，无惧困难与压力，使命必达；\n3.拥有强烈的自驱力、好奇心与求知欲，勤于思考，逻辑清晰；\n4.具备良好的逻辑思维和分析能力，勤于思考和总结；\n5.不甘平凡，追求成功，渴望在销售领域大展宏图；\n\n我们更希望你：\n1.有销售类实习经验或自主创业经历；\n2.学生会、社团学生干部；\n3.对电子产品有深入了解和相关项目经验。\n\n学历要求：本科及以上",
    workCityName: "深圳",
    workCityCode: "10002",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 41.52941176,
    positionStatus: 0,
    idProjPosition: 505,
    projectPositionId: 512,
    projectPositionName: "销售管理培训生",
    projectPositionDesc:
      "如果你：\n-热爱挑战，渴望在实践中学习销售管理技能，挑战区域市场管理目标和销售目标；\n-热爱探索，不断开拓新兴市场，不断实践新运营之道，进行全球范围的区域性统筹管理；\n-渴望成功，有远大的抱负，不甘于平庸，期待更快的成长；\n那么，欢迎加入我们，成为一名OPPO销售管理培训生！\n\n加入我们，你将：\n-这里是OPPO销售精英成长的摇篮，以区域市场操盘为实践主线，辅以渠道、零售、GTM等销售职能模块的历练，建立对销售领域的全面认知；\n-接受系统化的专业培养，给予完善的销售领域课程培训，专家导师全程跟踪辅导，业务和管理能力全面覆盖；\n-快速成长为销售领域负责人，主导销售实战，助力OPPO销售业务成功。\n",
    projectPositionRequire:
      "1.性格外向，善于沟通，能快速建立社交圈；\n2.充满激情，热爱挑战，无惧困难与压力，使命必达；\n3.拥有强烈的自驱力、好奇心与求知欲，勤于思考，逻辑清晰；\n4.具备良好的逻辑思维和分析能力，勤于思考和总结；\n5.不甘平凡，追求成功，渴望在销售领域大展宏图；\n\n我们更希望你：\n1.有销售类实习经验或自主创业经历；\n2.学生会、社团学生干部；\n3.对电子产品有深入了解和相关项目经验。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 538,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 545,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Hardware_class",
    positionTypeName: "硬件类",
    positionName: "硬件工程师（功耗方向）",
    positionDesc:
      "在这里，你将接触最前沿的硬件技术和行业最顶尖的硬件合作伙伴，通过技术创新不断为用户带去极致超长续航体验！低发热和超长续航是手机的核心体验竞争力，我们致力打造手机行业领先的低功耗竞争力。\n我们的技术方向涉及芯片/模组端、芯片与整机耦合，软硬结合、市场洞察，数据模型优化。通过技术进步与创新给消费者带去极致的长续航与低发热体验。在这里，你必定能够实现心中的梦想，让你设计的产品遍布世界每个角落，Created in China！\n具体工作方向包括：\n负责手机产品、智能穿戴及IOT产品的电子器件和传感器选型，硬件方案设计，软硬件联合调试，保证整机硬件性能和可靠性。",
    positionRequire:
      "1.集成电路、微电子、计算机等相关专业；\n2.熟练手机功耗自动化测试手段，并能将功耗逐级细分细分到每个器件功耗，对智能手机的CPU/GPU/DDR性能、能耗、DVFS调节有深入的研究；\n3.能对手机SOC的CPUL1/L2/L3cash、DDR的延时、带宽统计分析，并有一定的优化；\n4.对ARM体系结构，深入理解指令集、汇编、内存、中断、Coresight，调测要有较深的认知；\n5.能通过深入分析功耗测试数据并制定出最优的手机功耗、性能和热的平衡优化方案；\n6.能负责手机系统功耗、发热、稳定性技术问题攻关。\n\n学历要求：本科及以上",
    workCityName: "东莞",
    workCityCode: "10001",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 43.5,
    positionStatus: 0,
    idProjPosition: 538,
    projectPositionId: 545,
    projectPositionName: "硬件工程师（功耗方向）",
    projectPositionDesc:
      "在这里，你将接触最前沿的硬件技术和行业最顶尖的硬件合作伙伴，通过技术创新不断为用户带去极致超长续航体验！低发热和超长续航是手机的核心体验竞争力，我们致力打造手机行业领先的低功耗竞争力。\n我们的技术方向涉及芯片/模组端、芯片与整机耦合，软硬结合、市场洞察，数据模型优化。通过技术进步与创新给消费者带去极致的长续航与低发热体验。在这里，你必定能够实现心中的梦想，让你设计的产品遍布世界每个角落，Created in China！\n具体工作方向包括：\n负责手机产品、智能穿戴及IOT产品的电子器件和传感器选型，硬件方案设计，软硬件联合调试，保证整机硬件性能和可靠性。",
    projectPositionRequire:
      "1.集成电路、微电子、计算机等相关专业；\n2.熟练手机功耗自动化测试手段，并能将功耗逐级细分细分到每个器件功耗，对智能手机的CPU/GPU/DDR性能、能耗、DVFS调节有深入的研究；\n3.能对手机SOC的CPUL1/L2/L3cash、DDR的延时、带宽统计分析，并有一定的优化；\n4.对ARM体系结构，深入理解指令集、汇编、内存、中断、Coresight，调测要有较深的认知；\n5.能通过深入分析功耗测试数据并制定出最优的手机功耗、性能和热的平衡优化方案；\n6.能负责手机系统功耗、发热、稳定性技术问题攻关。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 552,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 557,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Purchasing",
    positionTypeName: "采购类",
    positionName: "资源开发经理",
    positionDesc:
      "在这里，你将获得与行业顶尖厂商接触的机会，你将学习到行业内先进的供应链管理体系，你将为打造伟大产品、助力产品表现力提升贡献你的一臂之力，你需要运用你的知识和能力保证物料全价值最优的采购。\n具体工作包括：\n1.制定物料全球采购策略，负责物料供应资源规划、成本、品质及交付管理；\n2.管理供应资源，助力公司打造伟大产品及战略目标落地。",
    positionRequire:
      "1.理工类（机械、材料、电子、微电子、化学、物理等）相关专业；\n2.英语六级以上，良好的英语应用能力；\n3.坚韧自信，具有较强的系统思考、影响说服能力。\n\n学历要求：本科及以上",
    workCityName: "东莞",
    workCityCode: "10001",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 71.25,
    positionStatus: 0,
    idProjPosition: 552,
    projectPositionId: 557,
    projectPositionName: "资源开发经理",
    projectPositionDesc:
      "在这里，你将获得与行业顶尖厂商接触的机会，你将学习到行业内先进的供应链管理体系，你将为打造伟大产品、助力产品表现力提升贡献你的一臂之力，你需要运用你的知识和能力保证物料全价值最优的采购。\n具体工作包括：\n1.制定物料全球采购策略，负责物料供应资源规划、成本、品质及交付管理；\n2.管理供应资源，助力公司打造伟大产品及战略目标落地。",
    projectPositionRequire:
      "1.理工类（机械、材料、电子、微电子、化学、物理等）相关专业；\n2.英语六级以上，良好的英语应用能力；\n3.坚韧自信，具有较强的系统思考、影响说服能力。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 524,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 530,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Engineering_Technology",
    positionTypeName: "工程技术类",
    positionName: "QA工程师",
    positionDesc:
      "在这里，你将获得为业内领先的智能终端提供技术支持的机会，同时你将深入掌控各种原材料的研发、制造、应用，你将运用你的知识和能力，为打造伟大产品，助力产品表现力贡献你的一臂之力，你将感受到最年轻化的团队作战氛围，加入我们，让我们一起迸发青春的火花， 让我们一起智造未来。\n具体工作方向包括：\n1.运用专业知识为产品质量改进服务；\n2.通过数据分析对接工艺/研发/制造各环节进行质量改善；\n3.推动产品质量问题解决，辅导供应商质量改善，保证品质一致性，打造伟大产品。",
    positionRequire:
      "1.电子、机械及材料相关专业本科及以上学历；\n2.熟悉模电、数电、通讯原理基础知识 、或熟悉机械类专业知识及塑胶件、五金件的制造工艺与一般性能要求；\n3.有良好的分析思维能力、沟通表达能力；\n我们更希望你：\n1.熟练英语听说读写，英语六级及以上；\n2.具备优秀的组织协调能力和团队合作能力，乐于奉献。\n\n学历要求：本科及以上",
    workCityName: "东莞",
    workCityCode: "10001",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 72,
    positionStatus: 0,
    idProjPosition: 524,
    projectPositionId: 530,
    projectPositionName: "QA工程师",
    projectPositionDesc:
      "在这里，你将获得为业内领先的智能终端提供技术支持的机会，同时你将深入掌控各种原材料的研发、制造、应用，你将运用你的知识和能力，为打造伟大产品，助力产品表现力贡献你的一臂之力，你将感受到最年轻化的团队作战氛围，加入我们，让我们一起迸发青春的火花， 让我们一起智造未来。\n具体工作方向包括：\n1.运用专业知识为产品质量改进服务；\n2.通过数据分析对接工艺/研发/制造各环节进行质量改善；\n3.推动产品质量问题解决，辅导供应商质量改善，保证品质一致性，打造伟大产品。",
    projectPositionRequire:
      "1.电子、机械及材料相关专业本科及以上学历；\n2.熟悉模电、数电、通讯原理基础知识 、或熟悉机械类专业知识及塑胶件、五金件的制造工艺与一般性能要求；\n3.有良好的分析思维能力、沟通表达能力；\n我们更希望你：\n1.熟练英语听说读写，英语六级及以上；\n2.具备优秀的组织协调能力和团队合作能力，乐于奉献。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 576,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 582,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Design",
    positionTypeName: "设计类",
    positionName: "动效设计师",
    positionDesc:
      "1.负责为 ColorOS 产品的用户界面设计动画方案，并推进落地，探索动画的实现方式，以提升设计方案的交互性和趣味性；\n2.参与设计流程优化，维护并完善动效设计标准，沉淀设计方法，制定规范；\n3.与团队成员共同进行行业研究，探索用户体验。",
    positionRequire:
      "1.设计、动画、影视、人机交互、信息设计、数字媒体艺术等相关专业；\n2.熟练掌握After Effects等动效设计工具，了解目前主流的UI设计工具（Figma、Sketch等）； \n3.理解动画的基本原理，了解基础的动效设计流程，具有较好的视觉、动效审美水平，能独立完成动效相关作品更佳；\n4.对用户体验具有一定了解，懂产品了解交互原理，善于捕捉流行趋势，有成功案例者优先；\n5.积极主动的学习能力，对设计行业的好奇心与探索，对用户体验的共情能力；\n6.工作积极负责，有良好的沟通能力和团队意识，具有较好的执行力；\n我们更希望你：\n1.了解掌握交互动效原型设计工具(ProtoPie、Framer、Principle等)；\n2.熟悉掌握常见的三维设计软件（Cinema 4D、Blender等），有建模、动画、渲染经验，并有较完整的作品展示。\n\n学历要求：本科及以上",
    workCityName: "深圳",
    workCityCode: "10002",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 110,
    positionStatus: 0,
    idProjPosition: 576,
    projectPositionId: 582,
    projectPositionName: "动效设计师",
    projectPositionDesc:
      "1.负责为 ColorOS 产品的用户界面设计动画方案，并推进落地，探索动画的实现方式，以提升设计方案的交互性和趣味性；\n2.参与设计流程优化，维护并完善动效设计标准，沉淀设计方法，制定规范；\n3.与团队成员共同进行行业研究，探索用户体验。",
    projectPositionRequire:
      "1.设计、动画、影视、人机交互、信息设计、数字媒体艺术等相关专业；\n2.熟练掌握After Effects等动效设计工具，了解目前主流的UI设计工具（Figma、Sketch等）； \n3.理解动画的基本原理，了解基础的动效设计流程，具有较好的视觉、动效审美水平，能独立完成动效相关作品更佳；\n4.对用户体验具有一定了解，懂产品了解交互原理，善于捕捉流行趋势，有成功案例者优先；\n5.积极主动的学习能力，对设计行业的好奇心与探索，对用户体验的共情能力；\n6.工作积极负责，有良好的沟通能力和团队意识，具有较好的执行力；\n我们更希望你：\n1.了解掌握交互动效原型设计工具(ProtoPie、Framer、Principle等)；\n2.熟悉掌握常见的三维设计软件（Cinema 4D、Blender等），有建模、动画、渲染经验，并有较完整的作品展示。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 542,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 549,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Comprehensive_functions",
    positionTypeName: "综合职能类",
    positionName: "海外财经管理专员",
    positionDesc:
      "工作内容涉及如下几个方向:\n1.海外项目预算管理与控制；\n2.财务报表编制及分析报告；\n3.业务财经/税务支持，提供业财解决方案；\n4.财务合规风险管控。",
    positionRequire:
      "1.会计学、财务管理、财政税收学等相关专业，专业知识扎实，在校成绩优异；\n2.外派印度及中东非等国家，需接受海外出差及派遣；\n3.品德优良、诚信本分踏实，有责任担当和团队精神；\n4.英语听说读写能力强，CET6、BEC中高级、雅思托福成绩优异者优先考虑。\n\n学历要求：本科及以上",
    workCityName: "深圳",
    workCityCode: "10002",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 110.4,
    positionStatus: 0,
    idProjPosition: 542,
    projectPositionId: 549,
    projectPositionName: "海外财经管理专员",
    projectPositionDesc:
      "工作内容涉及如下几个方向:\n1.海外项目预算管理与控制；\n2.财务报表编制及分析报告；\n3.业务财经/税务支持，提供业财解决方案；\n4.财务合规风险管控。",
    projectPositionRequire:
      "1.会计学、财务管理、财政税收学等相关专业，专业知识扎实，在校成绩优异；\n2.外派印度及中东非等国家，需接受海外出差及派遣；\n3.品德优良、诚信本分踏实，有责任担当和团队精神；\n4.英语听说读写能力强，CET6、BEC中高级、雅思托福成绩优异者优先考虑。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 573,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 577,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Design",
    positionTypeName: "设计类",
    positionName: "UI视觉设计师（软件产品方向）",
    positionDesc:
      "方向一：参与ColorOS系统组件设计，并定期更新维护系统设计规范；\n方向二：在系统型产品/工具型产品/运营型产品上能提出创新性的设计方案，支撑产品目标达成；\n方向三：主导制作OPPO商城、OPPO+ App 、OPPO官网（中国大陆）等市场营销平台的UI设计语言，基于用户体验及推广目标，定制全链路的设计工作，参与建立统一的UI界面设计语言。",
    positionRequire:
      "1.平面设计、视觉传达等艺术设计相关专业，综合素质扎实，热爱设计；\n2.能够熟练使用Skecth等设计软件，掌握Flinto，Principle等原型制作软件；\n3.在版式设计，字体设计，图像处理，UI等领域经验丰富；\n4.优秀的组织协调能力及沟通理解能力，执行能力高；能承受高强度的工作压力；\n5.优选条件：了解开发，有互联网社交App/销售类商场App/操作系统视觉设计等实习经验者优先。\n\n学历要求：本科及以上",
    workCityName: "深圳,成都",
    workCityCode: "10002,10006",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 135.33333333,
    positionStatus: 0,
    idProjPosition: 573,
    projectPositionId: 577,
    projectPositionName: "UI视觉设计师（软件产品方向）",
    projectPositionDesc:
      "方向一：参与ColorOS系统组件设计，并定期更新维护系统设计规范；\n方向二：在系统型产品/工具型产品/运营型产品上能提出创新性的设计方案，支撑产品目标达成；\n方向三：主导制作OPPO商城、OPPO+ App 、OPPO官网（中国大陆）等市场营销平台的UI设计语言，基于用户体验及推广目标，定制全链路的设计工作，参与建立统一的UI界面设计语言。",
    projectPositionRequire:
      "1.平面设计、视觉传达等艺术设计相关专业，综合素质扎实，热爱设计；\n2.能够熟练使用Skecth等设计软件，掌握Flinto，Principle等原型制作软件；\n3.在版式设计，字体设计，图像处理，UI等领域经验丰富；\n4.优秀的组织协调能力及沟通理解能力，执行能力高；能承受高强度的工作压力；\n5.优选条件：了解开发，有互联网社交App/销售类商场App/操作系统视觉设计等实习经验者优先。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 502,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 509,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Design",
    positionTypeName: "设计类",
    positionName: "UI视觉设计师（创新产品方向）",
    positionDesc:
      "1.负责AR和创新项目的视觉设计；\n2.负责设计前期分析、视觉风格设定；\n3.负责高保真产品原型设计和动态DEMO的实现；\n4.参与全链路的设计工作，建立体系的UI界面设计语言，主动找到设计的发力点，推动与执行设计方案的落地。",
    positionRequire:
      "1.平面设计、视觉传达、新媒体设计、三维动画设计、互动媒体设计、多媒体设计、游戏设计等相关专业；\n2.热爱创新，对前瞻技术有追求和一定的了解；\n3.美术功底扎实，较好的设计视野与审美，在图形、版式、字体设计、色彩方面有系统积累；\n4.掌握基础设计软件，熟练使用动效和3D软件者优先；\n5.具备良好的沟通能力，团队协作以及独立思考能力；\n6.激情、关注细节、学习能力强，善于组织协作与团队创造结果。\n\n学历要求：硕士及以上",
    workCityName: "深圳",
    workCityCode: "10002",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 154,
    positionStatus: 0,
    idProjPosition: 502,
    projectPositionId: 509,
    projectPositionName: "UI视觉设计师（创新产品方向）",
    projectPositionDesc:
      "1.负责AR和创新项目的视觉设计；\n2.负责设计前期分析、视觉风格设定；\n3.负责高保真产品原型设计和动态DEMO的实现；\n4.参与全链路的设计工作，建立体系的UI界面设计语言，主动找到设计的发力点，推动与执行设计方案的落地。",
    projectPositionRequire:
      "1.平面设计、视觉传达、新媒体设计、三维动画设计、互动媒体设计、多媒体设计、游戏设计等相关专业；\n2.热爱创新，对前瞻技术有追求和一定的了解；\n3.美术功底扎实，较好的设计视野与审美，在图形、版式、字体设计、色彩方面有系统积累；\n4.掌握基础设计软件，熟练使用动效和3D软件者优先；\n5.具备良好的沟通能力，团队协作以及独立思考能力；\n6.激情、关注细节、学习能力强，善于组织协作与团队创造结果。\n\n学历要求：硕士及以上",
    topNumber: 0,
  },
  {
    idRecruitPosition: 554,
    projectId: 10,
    atsProjectId: 10,
    atsProjectPositionId: 559,
    projectName: "2023届秋季校园招聘",
    recruitmentTypeName: "应届生",
    recruitmentType: "Graduate",
    positionType: "Design",
    positionTypeName: "设计类",
    positionName: "平面设计师",
    positionDesc:
      "1.承接全球品牌及营销相关素材制作和设计任务，能独立设计和协调各部门资源并有效沟通，达到设计表达和目的；\n2.能够基于产品定位和用户特性，把握品牌调性和设计趋势，产出产品创意设计方案；\n3.与内部设计团队以及跨部门密切合作，并在工作过程中遵照品牌需求与营销指引，以保证全球总体营销风格流畅统一。",
    positionRequire:
      "1.平面设计、视觉设计传达、插画设计、多媒体设计、广告学等相关专业；\n2.熟练使用视觉语言，其中包括符号、图像设计、字体、排版布局、影像、交互与艺术等；\n3.通晓基本的设计理论，对于色彩搭配、质感表现等功力扎实，并能把我最新的设计趋势与潮流；\n4.熟练使用Adobe Creative Cloud；\n5.注重细节，能适应快节奏工作， 具有优秀的沟通能力与组织能力；\n6.英语优秀，可作为工作语言；\n7.简历中请务必附上个人近期作品或者作品链接（有摄影经验为加分项）。\n\n学历要求：本科及以上",
    workCityName: "深圳",
    workCityCode: "10002",
    workCityVOList: null,
    positionNum: 2,
    proportionSort: 243.33333333,
    positionStatus: 0,
    idProjPosition: 554,
    projectPositionId: 559,
    projectPositionName: "平面设计师",
    projectPositionDesc:
      "1.承接全球品牌及营销相关素材制作和设计任务，能独立设计和协调各部门资源并有效沟通，达到设计表达和目的；\n2.能够基于产品定位和用户特性，把握品牌调性和设计趋势，产出产品创意设计方案；\n3.与内部设计团队以及跨部门密切合作，并在工作过程中遵照品牌需求与营销指引，以保证全球总体营销风格流畅统一。",
    projectPositionRequire:
      "1.平面设计、视觉设计传达、插画设计、多媒体设计、广告学等相关专业；\n2.熟练使用视觉语言，其中包括符号、图像设计、字体、排版布局、影像、交互与艺术等；\n3.通晓基本的设计理论，对于色彩搭配、质感表现等功力扎实，并能把我最新的设计趋势与潮流；\n4.熟练使用Adobe Creative Cloud；\n5.注重细节，能适应快节奏工作， 具有优秀的沟通能力与组织能力；\n6.英语优秀，可作为工作语言；\n7.简历中请务必附上个人近期作品或者作品链接（有摄影经验为加分项）。\n\n学历要求：本科及以上",
    topNumber: 0,
  },
];

console.log(jobs);
